cpps = Bonus.cpp Cheat.cpp Gamemap.cpp Hostbase.cpp Hostsingle.cpp Hostmulti.cpp Instream.cpp Log.cpp Observer.cpp main.cpp Player.cpp Simulation.cpp Subject.cpp
a.exe : $(cpps)
    g++ Bonus.cpp Cheat.cpp Gamemap.cpp Hostbase.cpp Hostsingle.cpp Hostmulti.cpp Instream.cpp Log.cpp Observer.cpp main.cpp Player.cpp Simulation.cpp Subject.cpp
 -o a.exe

